title: Jan Bode
tagline: Personal Website
description: ''
url: https://jan.bod3.de/
custom_domain: 'True'
baseurl: ''
google_analytics_id: G-DHPYNS7ET1
github_username: bodejan
gitlab_username: null
stackoverflow_username: null
researchgate_username: Jan-Bode-3
medium_username: null
behance_username: null
twitter_username: null
youtube_username: null
facebook_username: null
instagram_username: jan_bodee
linkedin_username: bode-jan
author:
  name: Jan Bode
  url: jan.bod3.de
  email: jan@bod3.de
paginate: 5
permalink: pretty
plugins:
- jekyll-paginate
version: 1.1.0
