title: Jan Bode
tagline: Personal Website
description: ''
url: https://jan.bod3.de
baseurl: ''
paginate: 5
permalink: pretty
author:
  name: Jan Bode
  url: jan.bod3.de
  email: jan@bod3.de
plugins:
- jekyll-paginate
version: 1.1.0
google_analytics_id: G-DHPYNS7ET1